apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: solver-connection-urls-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "khalani/testnet/solver-connection-urls"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SEPOLIA_RPC_URL"
            objectAlias: "sepoliaRpcUrl"
          - path: "SEPOLIA_WS_URL"
            objectAlias: "sepoliaWsUrl"
          - path: "FUJI_RPC_URL"
            objectAlias: "fujiRpcUrl"
          - path: "FUJI_WS_URL"
            objectAlias: "fujiWsUrl"
          - path: "SETTLER_PRIVATE_KEY"
            objectAlias: "settlerPrivateKey"
          - path: "CCMM_PRIVATE_KEY"
            objectAlias: "ccmmPrivateKey"
          - path: "INTENTBOOK_MATCHMAKER_PRIVATE_KEY"
            objectAlias: "intentbookPrivateKey"
          - path: "SPOKE_CHAIN_CALLER_PRIVATE_KEY"
            objectAlias: "spokeChainCallerprivateKey"
  secretObjects:
    - data:
      - key: SEPOLIA_RPC_URL
        objectName: sepoliaRpcUrl
      - key: SEPOLIA_WS_URL
        objectName: sepoliaWsUrl
      - key: FUJI_RPC_URL
        objectName: fujiRpcUrl
      - key: FUJI_WS_URL
        objectName: fujiWsUrl
      - key: SETTLER_PRIVATE_KEY
        objectName: settlerPrivateKey
      - key: CCMM_PRIVATE_KEY
        objectName: ccmmPrivateKey
      - key: INTENTBOOK_MATCHMAKER_PRIVATE_KEY
        objectName: intentbookPrivateKey
      - key: SPOKE_CHAIN_CALLER_PRIVATE_KEY
        objectName: spokeChainCallerprivateKey
      secretName: solver-connection-urls
      type: Opaque