// This file is automatically generated and contains assets from mainnet.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
}



const assets: Assets = {
  stableAssets: [
    Address.fromString('0x47e4F578Baa6A63891Ee5Ba2D08fcf0c5b8d8307'),
    Address.fromString('0xb83dca5964b7FF263279c9f5f3E8E38728ea26Ba'),
    Address.fromString('0x1Fa37818ae2710C23301D94d2BeE37951C2DD55b'),
  ],
  pricingAssets: [],
};

export default assets;
