/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as migrationSol from "./Migration.sol";
export type { migrationSol };
import type * as yokaiErc20Sol from "./YokaiERC20.sol";
export type { yokaiErc20Sol };
import type * as yokaiFactorySol from "./YokaiFactory.sol";
export type { yokaiFactorySol };
import type * as yokaiPairSol from "./YokaiPair.sol";
export type { yokaiPairSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
