apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: khalani-testnet-nodes-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "khalani/testnet/nodes-private-keys"
        objectType: "secretsmanager"
        jmesPath:
          - path: "NODE_PRIVATE_KEY_1"
            objectAlias: "nodePrivateKey1"
          - path: "NODE_PRIVATE_KEY_2"
            objectAlias: "nodePrivateKey2"
          - path: "NODE_PRIVATE_KEY_3"
            objectAlias: "nodePrivateKey3"
          - path: "NODE_PRIVATE_KEY_4"
            objectAlias: "nodePrivateKey4"
  secretObjects:
    - data:
      - key: NODE_PRIVATE_KEY_1
        objectName: nodePrivateKey1
      - key: NODE_PRIVATE_KEY_2
        objectName: nodePrivateKey2
      - key: NODE_PRIVATE_KEY_3
        objectName: nodePrivateKey3
      - key: NODE_PRIVATE_KEY_4
        objectName: nodePrivateKey4
      secretName: khalani-testnet-nodes-private-keys
      type: Opaque