apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: khalani-faucet-captcha-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "khalani/faucet/googleCaptchaV3Secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "KHALANI_FAUCET_GOOGLE_CAPTCHA_V3_SECRET"
            objectAlias: "faucetGoogleCaptchaV3Secret"
  secretObjects:
    - data:
      - key: KHALANI_FAUCET_GOOGLE_CAPTCHA_V3_SECRET
        objectName: faucetGoogleCaptchaV3Secret
      secretName: khalani-faucet-google-captcha-v3
      type: Opaque