apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blockchain-rpcs-aws-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "khalani/testnet/hyperlane-connection-urls"
        objectType: "secretsmanager"
        jmesPath:
          - path: "HYP_CHAINS_KHALANITESTNET_TRIAL_CUSTOMRPCURLS"
            objectAlias: "khalaniConnectionUrl"
          - path: "HYP_CHAINS_FUJI_CUSTOMRPCURLS"
            objectAlias: "fujiConnectionUrl"
          - path: "HYP_CHAINS_SEPOLIA_CUSTOMRPCURLS"
            objectAlias: "sepoliaConnectionUrl"
  secretObjects:
    - data:
      - key: HYP_CHAINS_KHALANITESTNET_TRIAL_CUSTOMRPCURLS
        objectName: khalaniConnectionUrl
      - key: HYP_CHAINS_FUJI_CUSTOMRPCURLS
        objectName: fujiConnectionUrl
      - key: HYP_CHAINS_SEPOLIA_CUSTOMRPCURLS
        objectName: sepoliaConnectionUrl
      secretName: hyperlane-connection-urls
      type: Opaque