apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tvl-docker-ghcr-login-secret-aws-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "khalani/testnet/ghcr-login-secret"
        objectType: "secretsmanager"
        objectAlias: "ghcrLoginSecret"
  secretObjects:
    - data:
      - key: .dockerconfigjson
        objectName: ghcrLoginSecret
      secretName: ghcr-login-secret
      type: kubernetes.io/dockerconfigjson