[package]
name = "medusa-api"
version = "0.1.0"
edition = "2024"

[features]
default = ["medusa-storage/sqlite"]
test-with-postgres = [
    "medusa-storage/postgres",
    "medusa-storage/test-with-postgres",
]

[dependencies]
alloy.workspace = true
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
medusa-apm.workspace = true
medusa-apm-derive.workspace = true
medusa-storage.workspace = true
medusa-types.workspace = true
medusa-tx-worker.workspace = true
mockall.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bcs.workspace = true

[dev-dependencies]
alloy = { workspace = true, features = ["rand"] }
