module.exports = {
  roots: ['./'],
  preset: 'ts-jest',
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.jsx?$': 'ts-jest',
  },
  testRegex: `(/__tests__/.*|(\\.|/)(test))\\.[jt]sx?$`,
  transformIgnorePatterns: ['node_modules/(?!@hadouken-project/ui)'],
  moduleNameMapper: {
    '\\.svg$': '<rootDir>/__mocks__/svgrMock.js',
    '@assets/(.*)': '<rootDir>/public/$1',
    '@components/(.*)': '<rootDir>/src/components/$1',
    '@containers/(.*)': '<rootDir>/src/containers/$1',
    '@constants/(.*)': '<rootDir>/src/constants/$1',
    '@graph/(.*)': '<rootDir>/src/graph/$1',
    '@interfaces/(.*)': '<rootDir>/src/interfaces/$1',
    '@messages/(.*)': '<rootDir>/src/messages/$1',
    '@dataSource/(.*)': '<rootDir>/src/dataSource/$1',
    '@pages/(.*)': '<rootDir>/src/pages/$1',
    '@store/(.*)': '<rootDir>/src/store/$1',
    '@styles/(.*)': '<rootDir>/src/styles/$1',
    '@tests/(.*)': '<rootDir>/testUtils/$1',
    '@utils/(.*)': '<rootDir>/src/utils/$1',
    '@modules/(.*)': '<rootDir>/src/modules/$1',
    '@config': '<rootDir>/src/config.ts',
    '.+\\.(css|styl|less|sass|scss)$': 'identity-obj-proxy',
    '.+\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/file-mock.js',
  },
  coveragePathIgnorePatterns: ['<rootDir>/public/', '<rootDir>/testUtils/'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testPathIgnorePatterns: ['node_modules'],
  setupFilesAfterEnv: ['<rootDir>/setup-tests.ts'],
}
