# Training configuration
training:
  seed: 42
  batch_size: 256
  learning_rate: 0.001
  epochs: 500
  train_split: 0.8
  val_split: 0.1
  scheduler:
    type: 'ReduceLROnPlateau'
    factor: 0.5
    patience: 10
    min_lr: 1e-6

# Model configuration
model:
  type: 'spatial_influence'
  name: 'spatial_influence'
  grid_size: [32, 48]  # height, width
  initial_sigma: 5.0
  initial_delta_t: 1.0
  initial_friction: 0.1

# Data configuration
data:
  data_dir: 'data'

# Output configuration
output:
  base_dir: 'outputs' 