training:
  seed: 42
  batch_size: 256
  learning_rate: 0.004
  epochs: 5000
  train_split: 0.8
  val_split: 0.1
  scheduler:
    type: 'ReduceLROnPlateau'
    factor: 0.75
    patience: 130
    min_lr: 1e-6

model:
  type: 'triangle'
  name: 'triangle'
  grid_size: [25, 40]
  initial_sigma_player: 5.0
  initial_sigma_ball: 1.5
  initial_delta_t: 1.0
  initial_friction: 0.1
  goal_importance_sigma: 15.0
  slow_ball_threshold: 2.0
  defensive_cone_angle: 45.0


data:
  data_dir: 'data'

output:
  base_dir: 'outputs' 