[project]
name = "medusa-mcp"
version = "0.1.0"
description = "Medusa MCP Demo"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
    "toml>=0.10.2",
    "eth-abi>=4.2.1",
    "eth-utils>=5.2.0",
]
