apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "funding-bot.addressesConfigMapName" . }}
data:
  addresses.json: {{ required "Addresses to be monitored must be specified" .Values.fundingBot.addressesContent | toJson }}