apiVersion: v1
kind: Secret
metadata:
  name: {{ include "funding-bot.rpcUrlsSecret" . }}
type: Opaque
data:
  rpc-urls.json: {{ required "RPC URLs must be specified" .Values.fundingBot.rpcUrlsContent | b64enc }}