export enum StoreKeys {
  Backstop = 'Backstop',
  InitializeStore = 'InitializeStore',
  Network = 'Network',
  Provider = 'Provider',
  Balances = 'Balances',
  PricedBalances = 'PricedBalances',
  Wallet = 'Wallet',
  Pools = 'Pools',
  PoolsHistory = 'PoolsHistory',
  Tokens = 'Tokens',
  Prices = 'Prices',
  History = 'History',
  Swap = 'Swap',
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  UserShares = 'UserShares',
  Contracts = 'Contracts',
  Lending = 'Lending',
  PoolJoinsExits = 'PoolJoinsExits',
  PoolSwaps = 'PoolSwaps',
  LockDrop = 'LockDrop',
}
