[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts/',
    'hardhat/=node_modules/hardhat/',
    '@balancer-labs/=node_modules/@balancer-labs/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'hardhat/=node_modules/hardhat/',
    '@hyperlane-xyz/core=lib/hyperlane-monorepo/solidity/',
    '@sgn-v2-contracts=lib/sgn-v2-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
]

[rpc_endpoints]
godwoken_test = "${GODWOKEN_TESTNET_RPC_URL}"
godwoken_main = "${GODWOKEN_MAINNET_RPC_URL}"
axon = "{AXON_RPC_URL}"

[etherscan]
rinkeby = { key = "${ETHERSCAN_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
