name: CI (Test , Docker , Publish)

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  SEPOLIA_WS_URL: ${{ secrets.SEPOLIA_WS_URL }}
  FUJI_RPC_URL: ${{ secrets.FUJI_RPC_URL }}
  FUJI_WS_URL: ${{ secrets.FUJI_WS_URL }}
  CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
  CONFIG_FILE : ${{ github.workspace }}/config/config.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75
          profile: minimal
          components: rustfmt, clippy
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings



  docker:
    needs: test
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.repository}}:latest
