CLIENT_ID: SsKhEe9VqmA8cf5qx6kwvU0b
CLIENT_SECRET: 7PNhj9OhMmDl3kimiEGK7QyCSXIDCOEtwtWdlnYh7aWrLNGq
NEXT_PUBLIC_EZKL_HUB_URL: https://hub.ezkl.xyz
EZKL_HUB_URL: https://foo.ezkl.xyz
NEXTAUTH_EZKL_CLIENT_ID: 2dTiZjU0Eu5NtWoicyitABBc
NEXTAUTH_EZKL_CLIENT_SECRET: ki6VEoQn3B8xirY1S9SKOZlTSKCoQNqvIPIkM8o68RXMgula
NEXTAUTH_CLIENT_ID: 2dTiZjU0Eu5NtWoicyitABBc
NEXTAUTH_CLIENT_SECRET: ki6VEoQn3B8xirY1S9SKOZlTSKCoQNqvIPIkM8o68RXMgula
NEXTAUTH_URL: https://foo.ezkl.xyz/
NEXTAUTH_SECRET: secret
GITHUB_CLIENT_ID: Iv1.6dd9d4239d396c07
GITHUB_CLIENT_SECRET: fe9c127c0850d9beac3cd56782cf4ce7cbafc658