# Default values for wallet-balance-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fundingBot:
  interval: 60 # Seconds
  prometheusPushGatewayUrl: http://prometheus-stack-pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091
  minimumBalance: 2
  fundingAmount: "0.25"
  kms:
    awsRegion: "us-east-1"
    alias: "alias/khalani-bank"
  addressesContent:
  rpcUrlsContent:

replicaCount: 1

image:
  repository: ghcr.io/tvl-labs/funding-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: ghcr-login-secret
nameOverride: ""
fullnameOverride: ""

prometheusRule:
  enabled: true
  walletName: example
  chain: mainnet
  minimumBalance: 2

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {
    eks.amazonaws.com/role-arn: arn:aws:iam::803035318642:role/funding-bot
  }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "funding-bot"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
