name: Build and push docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        type: string
        default: 'dev'

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository without submodules first
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 4: Install Foundry (Forge)
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Step 5: Build contracts with Forge in the submodule
      - name: Build contracts with Forge
        run: |
          cd contracts
          forge build                    

      # Step 6: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: medusa/Dockerfile
          tags: ghcr.io/${{ github.repository }}/medusa:latest
          push: true
