name: Medusa CI Tests

on:
  pull_request:
    paths:
    - 'medusa/**'
  merge_group:
    paths:
    - 'medusa/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  dev-ci-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          medusa/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('medusa/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Check all code
      run: cargo check --all
      working-directory: medusa

    - name: Run unit tests
      run: cargo test --all
      working-directory: medusa

    # Postgres may have already been started on our self-hosted runner.
    - name: Start postgres
      run: docker run -d -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres || true

    - name: Run tests with postgres
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      run: cargo test -p medusa-storage -p medusa-api --features test-with-postgres
      working-directory: medusa

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install nightly toolchain and rustfmt
      run: rustup toolchain install nightly -c rustfmt

    - name: Run rustfmt check
      run: cargo +nightly fmt -- --check
      working-directory: medusa
