"""empty message

Revision ID: 0aa458fe0d57
Revises: 5700799ab9a6
Create Date: 2023-09-20 00:02:11.308774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa458fe0d57'
down_revision = '5700799ab9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_node_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('github_node_id')

    # ### end Alembic commands ###
