"""default_org

Revision ID: 2cfca57cd954
Revises: d32131b7b0df
Create Date: 2023-10-11 13:32:47.997401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfca57cd954'
down_revision = 'd32131b7b0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_organization', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('default_organization_of_user', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['default_organization_of_user'])
        batch_op.create_foreign_key(None, 'user', ['default_organization_of_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('default_organization_of_user')
        batch_op.drop_column('default_organization')

    # ### end Alembic commands ###
