"""empty message

Revision ID: 5700799ab9a6
Revises: dae6f4de82ad
Create Date: 2023-09-19 23:58:43.086070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5700799ab9a6'
down_revision = 'dae6f4de82ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_organizations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_organization_id_fkey', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_organization_id_fkey', 'organizations', ['organization_id'], ['id'])

    op.drop_table('user_organizations')
    # ### end Alembic commands ###
