"""empty message

Revision ID: 75daa57f2ff7
Revises: 0aa458fe0d57
Create Date: 2023-09-20 02:15:55.612045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75daa57f2ff7'
down_revision = '0aa458fe0d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_role_associations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'organization_id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    op.drop_table('user_role_associations')
    op.drop_table('roles')
    # ### end Alembic commands ###
