"""ondelete cascde

Revision ID: ba96e2fa14e8
Revises: 2cfca57cd954
Create Date: 2023-10-11 22:38:56.683103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba96e2fa14e8'
down_revision = '2cfca57cd954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_token', schema=None) as batch_op:
        batch_op.drop_constraint('access_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint('emails_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_constraint('refresh_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('refresh_tokens_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emails_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('access_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('access_tokens_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
