"""add proof model

Revision ID: e1c4fe007601
Revises: 1c5ee7298cdc
Create Date: 2023-10-12 03:22:53.659452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c4fe007601'
down_revision = '1c5ee7298cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('proof', sa.String(), nullable=True),
    sa.Column('_instances', sa.String(), nullable=True),
    sa.Column('transcript_type', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['proof.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('solidity_artifact', schema=None) as batch_op:
        batch_op.drop_constraint('solidity_artifact_artifact_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artifact', ['artifact_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solidity_artifact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('solidity_artifact_artifact_id_fkey', 'artifact', ['artifact_id'], ['id'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('proof')
    # ### end Alembic commands ###
