"""empty message

Revision ID: eb1cf95c49bb
Revises: dd78483d1977
Create Date: 2023-09-06 17:18:57.736396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1cf95c49bb'
down_revision = 'dd78483d1977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solidity_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('solidity_version', sa.String(), nullable=True),
    sa.Column('evm_version', sa.String(), nullable=True),
    sa.Column('optimizer_enabled', sa.Boolean(), nullable=True),
    sa.Column('optimizer_runs', sa.Integer(), nullable=True),
    sa.Column('solidity_code', sa.String(), nullable=True),
    sa.Column('byte_code', sa.String(), nullable=True),
    sa.Column('abi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solidity_code')
    # ### end Alembic commands ###
