{
 "title": "Relayers",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{namespace=\"hyperlane\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages processed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hyperlane_messages_processed_count",
     "legendFormat": "{{origin}} -> {{remote}} ({{service}})"
    }
   ]
  },
  {
   "title": "Blocks indexed in the last 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(hyperlane_block_height{agent=\"relayer\"}[3m])",
     "legendFormat": "{{service}} on {{chain}}"
    }
   ]
  },
  {
   "title": "Blocks scanned in the last 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(hyperlane_contract_sync_block_height[1m])",
     "legendFormat": "{{service}} ({{data_type}})"
    }
   ]
  },
  { "title": "Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Relayer balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "hyperlane_wallet_balance{agent=\"relayer\"}",
     "legendFormat": "{{service}} ({{chain}})"
    }
   ]
  }
 ]
}