{
 "title": "Validators",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "bucket", "label": "Avg Over", "query": "2m,5m,10m,30m,1h,1d,7d,30d" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(hyperlane_block_height, hyperlane_deployment)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(hyperlane_block_height{hyperlane_deployment=~\"$deployment\"}, chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Time",
   "type": "timeseries",
   "description": "Seconds between blocks for each chain",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / avg by(chain)(rate(hyperlane_block_height{hyperlane_deployment=~\"$deployment\",chain=~\"$chain\",agent=\"validator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Indexed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(hyperlane_block_height{agent=\"validator\", chain=\"$chain\"}[5m])",
     "legendFormat": "{{service}} on {{chain}}"
    }
   ]
  },
  {
   "title": "Outbox Index Signed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(chain) (hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_processed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Signed ($bucket)",
   "type": "timeseries",
   "description": "Count of messages signed per time window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (chain)(hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_processed\"}) - max by (chain)(hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_processed\"} offset $bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Observation Lag",
   "type": "timeseries",
   "description": "If running multiple validator instances, the difference between the latest and earliest observed checkpoints for each chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by(chain) (hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_observed\"}) - min by (chain)(hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_observed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsigned Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "max by(chain) (hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_observed\"}) - min by(chain) (hyperlane_latest_checkpoint{agent=\"validator\",  chain=~\"$chain\", phase=\"validator_processed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hyperlane_outbox_state{agent=\"validator\", }",
     "legendFormat": "{{chain}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Contract Calls ($bucket)",
   "type": "timeseries",
   "description": "Total number of contract calls made by chain for a period",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (chain)(increase(hyperlane_contract_call_count{ chain=~\"$chain\", agent=\"validator\"}[$bucket]))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Contract Calls",
   "type": "timeseries",
   "description": "The rate at which we are making contract calls.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (chain) (rate(hyperlane_contract_call_count{agent=\"validator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contract Call Duration",
   "type": "timeseries",
   "description": "The average contract call duration by chain",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (chain)(rate(hyperlane_contract_call_count{agent=\"validator\",chain=~\"$chain\"}[$__rate_interval]) - rate(hyperlane_contract_call_duration_seconds{agent=\"validator\",chain=~\"$chain\"}[$__rate_interval]))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Contract Calls $chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "chain",
   "collapsed": true,
   "panels": [
    {
     "title": "Contract Calls ($bucket)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (contract_name, function_name)(increase(hyperlane_contract_call_count{ chain=~\"$chain\", agent=\"validator\"}[$bucket]))",
       "legendFormat": "{{contract_name}}::{{function_name}}"
      }
     ]
    },
    {
     "title": "Contract Calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (function_name,contract_name)(rate(hyperlane_contract_call_count{agent=\"validator\",chain=~\"$chain\"}[$__rate_interval]))",
       "legendFormat": "{{contract_name}}::{{function_name}}"
      }
     ]
    },
    {
     "title": "Contract Call Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (function_name,contract_name)(rate(hyperlane_contract_call_count{agent=\"validator\",chain=~\"$chain\"}[$__rate_interval]) - rate(hyperlane_contract_call_duration_seconds{agent=\"validator\",chain=~\"$chain\"}[$__rate_interval]))",
       "legendFormat": "{{contract_name}}::{{function_name}}"
      }
     ]
    }
   ]
  }
 ]
}