module.exports = {
  roots: ['./'],
  preset: 'ts-jest',
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.jsx?$': 'ts-jest',
  },
  testEnvironment: 'jsdom',
  testRegex: `(/__tests__/.*|(\\.|/)(saga.test|spec|network.test|component.test))\\.[jt]sx?$`,
  transformIgnorePatterns: [
    'node_modules/(?!@(tvl-labs/sdk|tvl-labs/khalani-ui))',
  ],
  moduleNameMapper: {
    '\\.svg$': '<rootDir>/__mocks__/svgrMock.js',
    '\\.png$': '<rootDir>/__mocks__/svgrMock.js',
    '@assets/(.*)': '<rootDir>/public/$1',
    '@components/(.*)': '<rootDir>/shared/components/$1',
    '@containers/(.*)': '<rootDir>/shared/containers/$1',
    '@constants/(.*)': '<rootDir>/shared/constants/$1',
    '@graph/(.*)': '<rootDir>/shared/graph/$1',
    '@interfaces/(.*)': '<rootDir>/shared/interfaces/$1',
    '@messages/(.*)': '<rootDir>/shared/messages/$1',
    '@dataSource/(.*)': '<rootDir>/shared/dataSource/$1',
    '@pages/(.*)': '<rootDir>/shared/pages/$1',
    '@hooks/(.*)': '<rootDir>/shared/hooks/$1',
    '@store/(.*)': '<rootDir>/shared/store/$1',
    '@styles/(.*)': '<rootDir>/shared/styles/$1',
    '@tests/(.*)': '<rootDir>/testUtils/$1',
    '@utils/(.*)': '<rootDir>/shared/utils/$1',
    '@libs/(.*)': '<rootDir>/shared/libs/$1',
    '@modules/(.*)': '<rootDir>/shared/modules/$1',
    '@shared/(.*)': '<rootDir>/shared/$1',
    '@config': '<rootDir>/shared/config.ts',
    '.+\\.(css|styl|less|sass|scss)$': 'identity-obj-proxy',
    '.+\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/file-mock.js',
    uuid: require.resolve('uuid'),
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testPathIgnorePatterns: ['node_modules'],
  setupFilesAfterEnv: ['<rootDir>/setup-tests.ts'],

  collectCoverage: true,
  coveragePathIgnorePatterns: [
    '.hooks.ts',
    'dataSource',
    'services/invest/serializers',
    'store/khala/balances/utils',
    'store/pool/selectors/models',
    '<rootDir>/public/',
    '<rootDir>/testUtils/',
  ],
  coverageDirectory: '<rootDir>/coverage/',
  verbose: false,
}
