name: BalancerJS Publish

on:
  release:
    types: [created]
    paths:
      - 'balancer-js/**'

env:
  NODE_VERSION: '16.x'
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: balancer-js

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 'Use Node.js v${{ env.NODE_VERSION }}'
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hadouken-project'

      - name: Install
        run: |
          yarn config set //npm.pkg.github.com/download/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          yarn config set @hadouken-project:registry https://npm.pkg.github.com
          yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn publish
