[workspace]
members = [
    # Prover
    #    We don't include `prove` image here since it cannot be built with stable rust
    #    and we don't want to use nightly for the whole workspace
    # "core/bin/prover",
    # Server
    "core/bin/zksync_core",
    "core/bin/external_node",
    "core/bin/system-constants-generator",
    "core/tests/cross_external_nodes_checker",
    # Contract verifier
    "core/bin/contract-verifier",
    # Setup key generator and server: its commented as it cannot be built with stable rust.
    # "core/bin/setup_key_generator_and_server",
    # Verification key generator and server
    "core/bin/verification_key_generator_and_server",
    #"core/bin/witness_generator",
    # circuit synthesizer: its commented as it cannot be built with stable rust.
    # "core/bin/circuit_synthesizer",
    "core/bin/enumeration_indices_migration",
    # Libraries
    "core/lib/basic_types",
    "core/lib/config",
    "core/lib/contracts",
    "core/lib/crypto",
    "core/lib/circuit_breaker",
    "core/lib/dal",
    "core/lib/db_test_macro",
    "core/lib/eth_client",
    "core/lib/eth_signer",
    "core/lib/mempool",
    "core/lib/merkle_tree",
    "core/lib/object_store",
    "core/lib/mini_merkle_tree",
    "core/lib/prometheus_exporter",
    "core/lib/queued_job_processor",
    "core/lib/state",
    "core/lib/storage",
    "core/lib/types",
    "core/lib/prover_utils",
    "core/lib/utils",
    "core/lib/vlog",
    "core/lib/vm",
    "core/lib/multivm",
    "core/lib/web3_decl",

    # MultiVM dependencies
    "core/multivm_deps/vm_m5",
    "core/multivm_deps/vm_m6",

    # Test infrastructure
    "core/tests/loadnext",
    "core/tests/vm-benchmark",
    "core/tests/vm-benchmark/harness",

    # SDK section
    "sdk/zksync-rs",
]
resolver = "2"

exclude = []

# for `perf` profiling
[profile.perf]
inherits = "release"
debug = true
