/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
import type * as iwethSol from "./IWETH.sol";
export type { iwethSol };
import type * as iYokaiRouter01Sol from "./IYokaiRouter01.sol";
export type { iYokaiRouter01Sol };
import type * as iYokaiRouter02Sol from "./IYokaiRouter02.sol";
export type { iYokaiRouter02Sol };
