name: Code coverage

on:
  pull_request:
    branches:
      - develop

env:
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 'Use Node.js v${{ env.NODE_VERSION }}'
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tvl-labs'

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-npm-cache-rf-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-rf

      - name: Install yarn dependencies
        run: |
          yarn config set //npm.pkg.github.com/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          yarn config set @tvl-labs:registry https://npm.pkg.github.com
          yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}

      - name: Run the tests
        run: yarn test --coverage

      - name: Report coverage
        uses: mszlgr/lcov-reporter-action@b638f6d2139b96561c26f029e1a31ac37210e960
        with:
          lcov-file: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
