apiVersion: v1
kind: ConfigMap
metadata:
  name: safe-txs-godwoken-mainnet
data:
  PYTHONPATH: "/app/"
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DEBUG: "0"
  ETHEREUM_NODE_URL: "https://v1.mainnet.godwoken.io/rpc"
  ETH_L2_NETWORK: "1"
  REDIS_URL: "redis://safe-txs-godwoken-mainnet.applications.svc.cluster.local:6379/0"
  CELERY_BROKER_URL: "amqp://guest:guest@safe-txs-godwoken-mainnet.applications.svc.cluster.local/"
  DJANGO_ALLOWED_HOSTS: "*"
  FORCE_SCRIPT_NAME: "/txs-godwoken-mainnet/"
  CSRF_TRUSTED_ORIGINS: "https://localhost.{{ .Values.domainName }}"