apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: django-secret-key-godwoken-testnet-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: {{ required "Secret Key name is required" .Values.secrets.txsGodwokenTestnetDjangoSecretKey }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - data:
      - key: password
        objectName: password
      secretName: django-secret-key-godwoken-testnet
      type: Opaque