apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-cfg-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: {{ required "DB Secret name is required" .Values.cfgDbSecretName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "dbUsername"
          - path: "password"
            objectAlias: "dbPassword"
  secretObjects:
    - data:
      - key: postgres_user
        objectName: dbUsername
      - key: postgres_pass
        objectName: dbPassword
      secretName: db-cfg-secret
      type: Opaque