apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: django-auth-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: {{ required "Django Auth secret name is required" .Values.djangoAuthSecretName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - data:
      - key: username
        objectName: username
      - key: password
        objectName: password
      secretName: django-auth-secret
      type: Opaque