apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cgw-rocket-secret-key-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: {{ required "Secret Key name is required" .Values.secrets.cgwRocketSecretKey }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - data:
      - key: password
        objectName: password
      secretName: cgw-rocket-secret-key
      type: Opaque