apiVersion: v1
kind: Service
metadata:
  name: safe-cfg-web
spec:
  selector:
    app: safe-cfg-web
  ports:
    - name: nginx
      port: 8000
      targetPort: 8000
    - name: cfg-web
      port: 8001
      targetPort: 8001