apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "safe.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "IAM role arn must be set in annotation" .Values.iamRoleArn }}