apiVersion: v1
kind: Service
metadata:
  name: safe-txs-khalani-testnet
spec:
  selector:
    app: safe-txs-khalani-testnet
  ports:
    - name: web
      port: 8888
      targetPort: 8888
    - name: redis
      port: 6379
      targetPort: 6379
    - name: celery
      port: 5672
      targetPort: 5672