{{- $fullName := include "graph-node.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-public
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: graph-node-http-khalani.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graph-node-external-open
                port:
                  number: 8000