{{- $fullName := include "graph-node.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-authenticated
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://ingress-external-auth.graph-node.svc.cluster.local:8080/auth
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: graph-node-admin-khalani.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graph-node
                port:
                  number: 8020