{{ $count := (add .Values.chainsCount 1 | int) }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: connection-urls-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "khalani/testnet/graph-connection-urls"
        objectType: "secretsmanager"
        jmesPath:
          {{- range untilStep 1 $count 1}}
          - path: "Chain{{ . }}Name"
            objectAlias: "Chain{{ . }}Name"
          - path: "Chain{{ . }}RpcUrl"
            objectAlias: "Chain{{ . }}RpcUrl"
          {{- end }}
   
  secretObjects:
    - data:
      {{- range untilStep 1 $count 1}}
      - key: Chain{{ . }}Name
        objectName: Chain{{ . }}Name
      - key: Chain{{ . }}RpcUrl
        objectName: Chain{{ . }}RpcUrl
      {{- end }}
      secretName: connection-urls
      type: Opaque