apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-bearer-token-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: {{ required "Graph access token secret name" .Values.graphAccessTokenSecretName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "config"
            objectAlias: "config"
  secretObjects:
    - data:
      - key: config
        objectName: config
      secretName: auth-bearer-token-secret
      type: Opaque