apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graph-node.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Graph Node IAM role arn must be set in annotation" .Values.iamRoleArn }}