version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:v0.27.0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres-graph
    environment:
      postgres_host: postgres-graph
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      # Change next line if you want to connect to a different JSON-RPC endpoint
      ethereum: "lending-godwoken-testnet:no_eip1898,archive,traces:https://godwoken-testnet-v1.ckbapp.dev/"
      GRAPH_LOG: info
      GRAPH_ETHEREUM_CLEANUP_BLOCKS: "true"
      GRAPH_GETH_ETH_CALL_ERRORS: 'revert;Error;cannot estimate gas;Failed to submit transaction: cannot estimate gas;ServerError(3);Failed to submit transaction;String("cannot estimate gas")'
      GRAPH_ETHEREUM_REQUESTS_RETRIES: 2

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"
  postgres-graph:
    image: postgres
    ports:
      - "5400:5432"
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
