/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as yokaiRouterSol from "./YokaiRouter.sol";
export type { yokaiRouterSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
