[package]
name = "mirax-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace.workspace = true
flume.workspace = true
log.workspace = true
smol_str.workspace = true
tokio.workspace = true
thiserror.workspace = true
trait-variant.workspace = true

mirax-api.workspace = true
mirax-db.workspace = true
mirax-compat.workspace = true
mirax-config.workspace = true
mirax-consensus.workspace = true
mirax-consensus-traits.workspace = true
mirax-crypto.workspace = true
mirax-error.workspace = true
mirax-mempool.workspace = true
mirax-network.workspace = true
mirax-narwhal.workspace = true
mirax-signal.workspace = true
mirax-signer.workspace = true
mirax-spec.workspace = true
mirax-storage.workspace = true
mirax-storage-traits.workspace = true
mirax-types.workspace = true
mirax-verification.workspace = true
mirax-version.workspace = true
