/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
import type * as iYokaiCalleeSol from "./IYokaiCallee.sol";
export type { iYokaiCalleeSol };
import type * as iYokaiErc20Sol from "./IYokaiERC20.sol";
export type { iYokaiErc20Sol };
import type * as iYokaiFactorySol from "./IYokaiFactory.sol";
export type { iYokaiFactorySol };
import type * as iYokaiPairSol from "./IYokaiPair.sol";
export type { iYokaiPairSol };
