networks:
  test:
    driver: bridge

services:
  miner1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-miner-M111
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: miner
      WALLET_NAME: Bistro
      WALLET_HOTKEY: M111
      CUDA_DEVICE: cuda:0
      NETWORK: test
      DEBUG: 'true'
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 268
      HOST_CUDA_VERSION: 12.6
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_READ_ACCESS_KEY_ID: ${R2_READ_ACCESS_KEY_ID}
      R2_READ_SECRET_ACCESS_KEY: ${R2_READ_SECRET_ACCESS_KEY}
      R2_WRITE_ACCESS_KEY_ID: ${R2_WRITE_ACCESS_KEY_ID}
      R2_WRITE_SECRET_ACCESS_KEY: ${R2_WRITE_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '3' ]
              capabilities: [ gpu ]

  miner2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-miner-M222
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: miner
      WALLET_NAME: Bistro
      WALLET_HOTKEY: M222
      CUDA_DEVICE: cuda:0
      NETWORK: test
      DEBUG: 'true'
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 268
      HOST_CUDA_VERSION: 12.6
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_READ_ACCESS_KEY_ID: ${R2_READ_ACCESS_KEY_ID}
      R2_READ_SECRET_ACCESS_KEY: ${R2_READ_SECRET_ACCESS_KEY}
      R2_WRITE_ACCESS_KEY_ID: ${R2_WRITE_ACCESS_KEY_ID}
      R2_WRITE_SECRET_ACCESS_KEY: ${R2_WRITE_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  validator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-validator-V11
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: validator
      WALLET_NAME: Bistro
      WALLET_HOTKEY: V11
      CUDA_DEVICE: cuda:0
      NETWORK: test
      DEBUG: 'true'
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 268
      HOST_CUDA_VERSION: 12.6
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_READ_ACCESS_KEY_ID: ${R2_READ_ACCESS_KEY_ID}
      R2_READ_SECRET_ACCESS_KEY: ${R2_READ_SECRET_ACCESS_KEY}
      R2_WRITE_ACCESS_KEY_ID: ${R2_WRITE_ACCESS_KEY_ID}
      R2_WRITE_SECRET_ACCESS_KEY: ${R2_WRITE_SECRET_ACCESS_KEY}
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '2' ]
              capabilities: [ gpu ]
