[package]
name = "medusa-apm-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case.workspace = true
fut-ret.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
async-trait.workspace = true
jsonrpsee.workspace = true
log.workspace = true
medusa-apm.workspace = true
medusa-types.workspace = true
serde.workspace = true
