name: 'Deploy Landing'

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '18.x'
  AWS_EC2_METADATA_DISABLED: true

jobs:
  landing_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 'Use Node.js v${{ env.NODE_VERSION }}'
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install yarn dependencies
        run: |
          yarn config set //npm.pkg.github.com/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          yarn config set @tvl-labs:registry https://npm.pkg.github.com
          yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}

      - name: 'Build Khala Landing'
        run: yarn build

      - name: 'Deploy Khala Landing'
        run: |
          aws s3 sync build s3://${{ secrets.S3_BUCKET }} --delete --exact-timestamps
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
