name: Publish to Github Packages

on:
  release:
    types: [created]
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GODWOKEN_DEPLOYER: '0x0000000000000000000000000000000000000000'
  MANTLE_DEPLOYER: '0x0000000000000000000000000000000000000000'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hadouken-project'
          always-auth: true

      - run: yarn
      - run: yarn typechain:godwoken
      - run: yarn typechain:zksync
      - run: yarn build
      - run: yarn config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - run: yarn config set @hadouken-project:registry https://npm.pkg.github.com
      - run: yarn publish
