name: 'Deploy Swap Application to Mainnet'

on:
  release:
    types: [created]

env:
  NODE_VERSION: '16.x'
  AWS_EC2_METADATA_DISABLED: true
  NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
  CONFIG: mainnet
  BASENAME: /swap

jobs:
  mainnet_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 'Use Node.js v${{ env.NODE_VERSION }}'
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install yarn dependencies
        run: |
          yarn config set //npm.pkg.github.com/download/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          yarn config set @hadouken-project:registry https://npm.pkg.github.com
          yarn --frozen-lockfile

      - name: 'Build'
        run: yarn build

      - name: 'Deploy'
        run: |
          aws s3 sync dist s3://${{ secrets.PROD_S3_BUCKET }}/swap --delete --exact-timestamps
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
