[package]
name = "mirax-codec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcs.workspace = true
faster-hex.workspace = true
serde.workspace = true
thiserror.workspace = true

mirax-error.workspace = true
mirax-primitive.workspace = true
