apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "settler.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Khalani Solver IAM role arn must be set in annotation" .Values.iamRoleArn }}