name: Build and push docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        type: string
        default: 'dev'
jobs:
  build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository without submodules first
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      # Step 2: Set up SSH to access private submodule
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 3: Sync and update submodules with SSH access
      - name: Sync and update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge

      # Step 4: Install Foundry (Forge)
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Step 5: Build contracts with Forge in the submodule
      - name: Build contracts with Forge
        run: |
          cd contracts/arcadia-core-contracts   
          forge build                    

      # Step 6: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_REPO_TOKNE }}
    

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
          push: true
