/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc20Sol from "./IERC20.sol";
export * as iwethSol from "./IWETH.sol";
export * as iYokaiRouter01Sol from "./IYokaiRouter01.sol";
export * as iYokaiRouter02Sol from "./IYokaiRouter02.sol";
