[package]
name = "mirax-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

mirax-chain.workspace = true
mirax-config.workspace = true
mirax-crypto.workspace = true
mirax-error.workspace = true
mirax-logger.workspace = true
mirax-spec.workspace = true
mirax-types.workspace = true
