name: Test CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install npm dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.G_ACCESS_TOKEN }}" > $HOME/.npmrc
          echo "@hadouken-project:registry=https://npm.pkg.github.com/" >> $HOME/.npmrc
          npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        if: always()
        run: npm run build --if-present

      - name: Run tests
        run: npm run test

      - name: npm install depedencies for infrastructure
        working-directory: ./infra
        run: npm ci

      - name: Run infrastructure tests
        working-directory: ./infra
        run: docker-compose run test-runner
