[package]
name = "mirax-primitive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives.workspace = true
bytes.workspace = true
derive_more.workspace = true
faster-hex.workspace = true
serde.workspace = true
smol_str.workspace = true
thiserror.workspace = true
zeroize.workspace = true

mirax-error.workspace = true

[dev-dependencies]
serde_json.workspace = true
toml.workspace = true
