[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"
optimizer = true
via_ir = true

fs_permissions = [{ access = "read", path = "./" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [

    "@openzeppelin/contracts=lib/oz4/contracts/",
    "@oz5/contracts=lib/openzeppelin-contracts/contracts/",
    "@hyperlane-xyz/core/contracts/=lib/hyperlane-monorepo/solidity/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "permit2/=lib/permit2/",
]
