"""ondelete cascade for org

Revision ID: 1c5ee7298cdc
Revises: ba96e2fa14e8
Create Date: 2023-10-11 22:40:18.207470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5ee7298cdc'
down_revision = 'ba96e2fa14e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint('organization_default_organization_of_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['default_organization_of_user'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('organization_default_organization_of_user_fkey', 'user', ['default_organization_of_user'], ['id'])

    # ### end Alembic commands ###
