"""empty message

Revision ID: 1f3e6e6dd099
Revises: 75daa57f2ff7
Create Date: 2023-09-20 02:43:07.422662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3e6e6dd099'
down_revision = '75daa57f2ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_edit_role_association',
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('artifact_view_role_association',
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_column('public')

    op.drop_table('artifact_view_role_association')
    op.drop_table('artifact_edit_role_association')
    # ### end Alembic commands ###
