"""empty message

Revision ID: 2fdb20effc3f
Revises: f4832c905dad
Create Date: 2023-09-08 04:30:37.666235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdb20effc3f'
down_revision = 'f4832c905dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncompiled_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('uncompiled_model_uploaded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('uncompiled_model_validated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_column('uncompiled_model_validated')
        batch_op.drop_column('uncompiled_model_uploaded')
        batch_op.drop_column('uncompiled_model')

    # ### end Alembic commands ###
