apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elijah.name }}
  labels:
    app: {{ .Values.elijah.name }}
spec:
  type: {{ .Values.elijah.service.type }}
  ports:
    - port: {{ .Values.elijah.service.port }}
      targetPort: {{ .Values.elijah.service.port }}
  selector:
    app: {{ .Values.elijah.name }}