[package]
name = "medusa-config"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy.workspace = true
config.workspace = true
serde.workspace = true
serde_json.workspace = true
aws-sdk-kms.workspace = true
aws-config.workspace = true
aws-types.workspace = true
anyhow.workspace = true
