# apiVersion: v1
# kind: Secret
# metadata:
#   name: flask-secrets
# type: Opaque
# data:
# {{- $env := .Files.Get "../../.env-prod" | split "\n" }}
# {{- range $line := $env }}
# {{- $parts := splitList "=" $line }}
# {{- if gt (len $parts) 1 }}
#   {{ index $parts 0 }}: {{ index $parts 1 | b64enc | quote }}
# {{- end }}
# {{- end }}