apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ezklterhubstagingregistry.azurecr.io/frontend:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ezkl-secrets
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: {}

