apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/load-balance: least_conn
spec:
  rules:
  - host: hub.ezkl.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-server-service
            port:
              number: 80
  - host: foo.ezkl.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
  tls:
  - hosts:
    - hub.ezkl.xyz
    - foo.ezkl.xyz
    secretName: cloudflare-tls-secret