apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallet-balance-monitor.addressesConfigMapName" . }}
data:
  addresses.json: {{ required "Addresses to be monitored must be specified" .Values.walletBalanceMonitor.addressesContent | toJson }}