apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-balance-monitor.rpcUrlsSecret" . }}
type: Opaque
data:
  rpc-urls.json: {{ required "RPC URLs must be specified" .Values.walletBalanceMonitor.rpcUrlsContent | b64enc }}