/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWETHAbi,
  IWETHAbiInterface,
} from "../../../../contracts/interfaces/IWETH.sol/IWETHAbi";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWETHAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IWETHAbiInterface {
    return new utils.Interface(_abi) as IWETHAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWETHAbi {
    return new Contract(address, _abi, signerOrProvider) as IWETHAbi;
  }
}
