/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc20Sol from "./IERC20.sol";
export * as iYokaiCalleeSol from "./IYokaiCallee.sol";
export * as iYokaiErc20Sol from "./IYokaiERC20.sol";
export * as iYokaiFactorySol from "./IYokaiFactory.sol";
export * as iYokaiPairSol from "./IYokaiPair.sol";
