name: 'CI'

on: push

env:
  NODE_VERSION: '18.x'
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
jobs:
  webapp_ci:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 'Use Node.js v${{ env.NODE_VERSION }}'
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tvl-labs'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-npm-cache-rf-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-rf

      - name: Install yarn dependencies
        run: |
          yarn --frozen-lockfile

      - name: Install yarn dependencies (standalone)
        run: |
          yarn --frozen-lockfile
        working-directory: standalone

      - name: Typecheck
        run: yarn typecheck

      - run: yarn test
