name: Publish SDK to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tvl-labs'
          always-auth: true

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build SDK
        run: yarn build

      - name: Configure Yarn authentication
        run: |
          yarn config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          yarn config set @tvl-labs:registry https://npm.pkg.github.com

      - name: Publish to GitHub Packages
        run: yarn publish --non-interactive
