name: CI

on:
  pull_request:
  merge_group:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.84.1
          default: true
          profile: minimal
          components: rustfmt, clippy

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-targets --locked -- -D warnings

      - name: clippy (all features)
        run: cargo clippy --all --all-features --all-targets --locked -- -D warnings

      - name: test
        run: cargo test --all --all-features
