export enum StoreKeys {
  Provider = 'Provider',
  SDK = 'SDK',
  Tokens = 'Tokens',
  Allowance = 'Allowance',
  Balances = 'Balances',
  Chains = 'Chains',
  Prices = 'Prices',
  NativeBalances = 'NativeBalances',
  Approve = 'Approve',
  Safe = 'Safe',
  TransactionHistory = 'TransactionHistory',
  CreateIntent = 'CreateIntent',
  CreateRefine = 'CreateRefine',
  QueryRefine = 'QueryRefine',
  LiquidityHistory = 'LiquidityHistory',
  BridgeHistory = 'BridgeHistory',
  MTokenBalances = 'MTokenBalances',
  WithdrawMToken = 'WithdrawMToken',
  WithdrawIntentBalance = 'WithdrawIntentBalance',
  IntentBalances = 'IntentBalances',
  Intents = 'Intents',
  Deposit = 'Deposit',
  DepositHistory = 'DepositHistory',
}
