/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { SwapTemplateBase } from "../SwapTemplateBase";

export class SwapTemplateBase__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SwapTemplateBase {
    return new Contract(address, _abi, signerOrProvider) as SwapTemplateBase;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "buyer",
      },
      {
        type: "int128",
        indexed: false,
        name: "sold_id",
      },
      {
        type: "uint256",
        indexed: false,
        name: "tokens_sold",
      },
      {
        type: "int128",
        indexed: false,
        name: "bought_id",
      },
      {
        type: "uint256",
        indexed: false,
        name: "tokens_bought",
      },
    ],
    name: "TokenExchange",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "provider",
      },
      {
        type: "uint256[]",
        indexed: false,
        name: "token_amounts",
      },
      {
        type: "uint256[]",
        indexed: false,
        name: "fees",
      },
      {
        type: "uint256",
        indexed: false,
        name: "invariant",
      },
      {
        type: "uint256",
        indexed: false,
        name: "token_supply",
      },
    ],
    name: "AddLiquidity",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "provider",
      },
      {
        type: "uint256[]",
        indexed: false,
        name: "token_amounts",
      },
      {
        type: "uint256[]",
        indexed: false,
        name: "fees",
      },
      {
        type: "uint256",
        indexed: false,
        name: "token_supply",
      },
    ],
    name: "RemoveLiquidity",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "provider",
      },
      {
        type: "uint256",
        indexed: false,
        name: "token_amount",
      },
      {
        type: "uint256",
        indexed: false,
        name: "coin_amount",
      },
      {
        type: "uint256",
        indexed: false,
        name: "token_supply",
      },
    ],
    name: "RemoveLiquidityOne",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "provider",
      },
      {
        type: "uint256[]",
        indexed: false,
        name: "token_amounts",
      },
      {
        type: "uint256[]",
        indexed: false,
        name: "fees",
      },
      {
        type: "uint256",
        indexed: false,
        name: "invariant",
      },
      {
        type: "uint256",
        indexed: false,
        name: "token_supply",
      },
    ],
    name: "RemoveLiquidityImbalance",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "uint256",
        indexed: true,
        name: "deadline",
      },
      {
        type: "address",
        indexed: true,
        name: "admin",
      },
    ],
    name: "CommitNewAdmin",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "admin",
      },
    ],
    name: "NewAdmin",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "uint256",
        indexed: true,
        name: "deadline",
      },
      {
        type: "uint256",
        indexed: false,
        name: "fee",
      },
      {
        type: "uint256",
        indexed: false,
        name: "admin_fee",
      },
    ],
    name: "CommitNewFee",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "uint256",
        indexed: false,
        name: "fee",
      },
      {
        type: "uint256",
        indexed: false,
        name: "admin_fee",
      },
    ],
    name: "NewFee",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "uint256",
        indexed: false,
        name: "old_A",
      },
      {
        type: "uint256",
        indexed: false,
        name: "new_A",
      },
      {
        type: "uint256",
        indexed: false,
        name: "initial_time",
      },
      {
        type: "uint256",
        indexed: false,
        name: "future_time",
      },
    ],
    name: "RampA",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        type: "uint256",
        indexed: false,
        name: "A",
      },
      {
        type: "uint256",
        indexed: false,
        name: "t",
      },
    ],
    name: "StopRampA",
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        name: "_owner",
      },
      {
        type: "address[]",
        name: "_coins",
      },
      {
        type: "address",
        name: "_pool_token",
      },
      {
        type: "uint256",
        name: "_A",
      },
      {
        type: "uint256",
        name: "_fee",
      },
      {
        type: "uint256",
        name: "_admin_fee",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "A",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "A_precise",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_virtual_price",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256[]",
        name: "_amounts",
      },
      {
        type: "bool",
        name: "_is_deposit",
      },
    ],
    name: "calc_token_amount",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256[]",
        name: "_amounts",
      },
      {
        type: "uint256",
        name: "_min_mint_amount",
      },
    ],
    name: "add_liquidity",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "int128",
        name: "i",
      },
      {
        type: "int128",
        name: "j",
      },
      {
        type: "uint256",
        name: "_dx",
      },
    ],
    name: "get_dy",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        type: "int128",
        name: "i",
      },
      {
        type: "int128",
        name: "j",
      },
      {
        type: "uint256",
        name: "_dx",
      },
      {
        type: "uint256",
        name: "_min_dy",
      },
    ],
    name: "exchange",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "_amount",
      },
      {
        type: "uint256[]",
        name: "_min_amounts",
      },
    ],
    name: "remove_liquidity",
    outputs: [
      {
        type: "uint256[]",
        name: "",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256[]",
        name: "_amounts",
      },
      {
        type: "uint256",
        name: "_max_burn_amount",
      },
    ],
    name: "remove_liquidity_imbalance",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "_token_amount",
      },
      {
        type: "int128",
        name: "i",
      },
    ],
    name: "calc_withdraw_one_coin",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "_token_amount",
      },
      {
        type: "int128",
        name: "i",
      },
      {
        type: "uint256",
        name: "_min_amount",
      },
    ],
    name: "remove_liquidity_one_coin",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "_future_A",
      },
      {
        type: "uint256",
        name: "_future_time",
      },
    ],
    name: "ramp_A",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stop_ramp_A",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "_new_fee",
      },
      {
        type: "uint256",
        name: "_new_admin_fee",
      },
    ],
    name: "commit_new_fee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "apply_new_fee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "revert_new_parameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "address",
        name: "_owner",
      },
    ],
    name: "commit_transfer_ownership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "apply_transfer_ownership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "revert_transfer_ownership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "i",
      },
    ],
    name: "admin_balances",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw_admin_fees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "donate_admin_fees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "kill_me",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unkill_me",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "arg0",
      },
    ],
    name: "coins",
    outputs: [
      {
        type: "address",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "arg0",
      },
    ],
    name: "balances",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fee",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "admin_fee",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        type: "address",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lp_token",
    outputs: [
      {
        type: "address",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initial_A",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "future_A",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initial_A_time",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "future_A_time",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "admin_actions_deadline",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "transfer_ownership_deadline",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "future_fee",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "future_admin_fee",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "future_owner",
    outputs: [
      {
        type: "address",
        name: "",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
