[package]
name = "mirax-signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeroize.workspace = true
mirax-crypto.workspace = true
mirax-types.workspace = true
