apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cross-chain-market-maker.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Khalani Solver IAM role arn must be set in annotation" .Values.iamRoleArn }}