[advisories]
version = 2
yanked = "deny"


[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-DFS-2016",
  "BSL-1.0",
]
# exceptions = [
#   { allow = [
#     "MIT",
#     "ISC",
#     "OpenSSL",
#   ], name = "ring", version = "*" },
# ]

# [[licenses.clarify]]
# name = "ring"
# version = "*"
# expression = "MIT AND ISC AND OpenSSL"
# license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

# [[licenses.clarify]]
# name = "encoding_rs"
# version = "*"
# expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
# license-files = [{ path = "COPYRIGHT", hash = 0x39f8ad31 }]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
