apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperlane-validator.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Validator IAM role must be set" .Values.validator.iamRoleArn }}