import { eContractid, IReserveParams } from '@src/types';
import { BigNumber } from 'ethers';
import {
  rateStrategyBTC,
  rateStrategyCKB,
  rateStrategyETH,
  rateStrategyMNT,
  rateStrategyUSDC,
  rateStrategyUSDT,
  rateStrategyWETH,
} from './rateStrategies';

interface Strategy extends IReserveParams {
  symbol: string;
}

export const strategies: Strategy[] = [
  {
    symbol: 'ETH.e',
    reserveDecimals: '18',
    strategy: rateStrategyETH,
    baseLTVAsCollateral: '3400',
    liquidationThreshold: '4400',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'MNT',
    reserveDecimals: '18',
    strategy: rateStrategyMNT,
    baseLTVAsCollateral: '3400',
    liquidationThreshold: '4400',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'WETH.e',
    reserveDecimals: '18',
    strategy: rateStrategyWETH,
    baseLTVAsCollateral: '3400',
    liquidationThreshold: '4400',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'BTC.e',
    reserveDecimals: '8',
    strategy: rateStrategyBTC,
    baseLTVAsCollateral: '3400',
    liquidationThreshold: '4400',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'WBTC.e',
    reserveDecimals: '8',
    strategy: rateStrategyBTC,
    baseLTVAsCollateral: '3400',
    liquidationThreshold: '4400',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'CKB',
    reserveDecimals: '18',
    strategy: rateStrategyCKB,
    baseLTVAsCollateral: '3400',
    liquidationThreshold: '4400',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'USDC.e',
    reserveDecimals: '6',
    strategy: rateStrategyUSDC,
    baseLTVAsCollateral: '3700',
    liquidationThreshold: '4700',
    liquidationBonus: '11000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
  {
    symbol: 'USDT.e',
    reserveDecimals: '6',
    strategy: rateStrategyUSDT,
    baseLTVAsCollateral: '0000',
    liquidationThreshold: '0000',
    liquidationBonus: '00000',
    reserveFactor: '1000',
    borrowingEnabled: true,
    supplyCap: BigNumber.from('20000000'),
    borrowCap: BigNumber.from('20000000'),
    stableBorrowRateEnabled: false,
    aTokenImpl: eContractid.AToken,
  },
];
