apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cluster-role
rules:
- apiGroups:
    - ""
  resources:
    - "namespaces"
  verbs:
    - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-cluster-role-binding
subjects:
- kind: User
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-cluster-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: axon
rules:
- apiGroups:
    - ""
  resources:
    - "configmaps"
    - "events"
    - "ingresses"
    - "jobs"
    - "nodes"
    - "persistentvolumeclaims"
    - "persistentvolumes"
    - "namespaces"
    - "pods"
    - "pods/log"
    - "secrets"
    - "services"
  verbs:
    - "describe"
    - "get"
    - "list"
- apiGroups:
    - "apps"
  resources:
    - "daemonsets"
    - "deployments"
    - "replicasets"
    - "statefulsets"
  verbs:
    - "describe"
    - "get"
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: axon
subjects:
- kind: User
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: hyperlane
rules:
- apiGroups:
    - ""
  resources:
    - "configmaps"
    - "events"
    - "ingresses"
    - "jobs"
    - "nodes"
    - "persistentvolumeclaims"
    - "persistentvolumes"
    - "namespaces"
    - "pods"
    - "pods/log"
    - "secrets"
    - "services"
  verbs:
    - "describe"
    - "get"
    - "list"
- apiGroups:
    - "apps"
  resources:
    - "daemonsets"
    - "deployments"
    - "replicasets"
    - "statefulsets"
  verbs:
    - "describe"
    - "get"
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: hyperlane
subjects:
- kind: User
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: monitoring
rules:
- apiGroups:
    - ""
  resources:
    - "configmaps"
    - "events"
    - "ingresses"
    - "jobs"
    - "nodes"
    - "persistentvolumeclaims"
    - "persistentvolumes"
    - "namespaces"
    - "pods"
    - "pods/log"
    - "secrets"
    - "services"
  verbs:
    - "describe"
    - "get"
    - "list"
- apiGroups:
    - ""
  resources:
    - "pods/portforward"
  verbs:
    - "get"
    - "list"
    - "create"
    - "update"
    - "delete"
    - "watch"
- apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - "customresourcedefinitions"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "apps"
  resources:
    - "daemonsets"
    - "deployments"
    - "replicasets"
    - "statefulsets"
  verbs:
    - "describe"
    - "get"
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: monitoring
subjects:
- kind: User
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: applications
rules:
- apiGroups:
    - ""
  resources:
    - "configmaps"
    - "events"
    - "ingresses"
    - "jobs"
    - "nodes"
    - "persistentvolumeclaims"
    - "persistentvolumes"
    - "namespaces"
    - "pods"
    - "pods/log"
    - "secrets"
    - "services"
  verbs:
    - "describe"
    - "get"
    - "list"
- apiGroups:
    - ""
  resources:
    - "pods/portforward"
  verbs:
    - "get"
    - "list"
    - "create"
    - "update"
    - "delete"
    - "watch"
- apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - "customresourcedefinitions"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "apps"
  resources:
    - "daemonsets"
    - "deployments"
    - "replicasets"
    - "statefulsets"
  verbs:
    - "describe"
    - "get"
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: applications
subjects:
- kind: User
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-role