apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: key-base-secret-class
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: {{ required "Key Base Secret name is required" .Values.keyBaseSecretName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - data:
      - key: password
        objectName: password
      secretName: key-base-secret
      type: Opaque