export enum StoreKeys {
  InitializeStore = 'InitializeStore',
  Network = 'Network',
  Chains = 'Chains',
  Provider = 'Provider',
  Balances = 'Balances',
  PricedBalances = 'PricedBalances',
  Wallet = 'Wallet',
  Pools = 'Pools',
  PoolsHistory = 'PoolsHistory',
  Tokens = 'Tokens',
  Prices = 'Prices',
  History = 'History',
  Swap = 'Swap',
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  Lock = 'Lock',
  UserShares = 'UserShares',
  Contracts = 'Contracts',
  CrossChainDeposit = 'CrossChainDeposit',
  Allowance = 'Allowance',
  Approve = 'Approve',
  KhalaTokens = 'KhalaTokens',
  KhalaBalances = 'KhalaBalances',
}
