[package]
name = "mirax-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
libp2p.workspace = true
serde.workspace = true
smol_str.workspace = true
thiserror.workspace = true

mirax-crypto.workspace = true
mirax-parser.workspace = true
mirax-types.workspace = true
