[package]
name = "arcadia-user-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
medusa-types = { path = "../types" }
medusa-service = { path = "../../" }
dotenv = "0.15"
tokio = { version = "1.34.0", features = ["full", "test-util"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonrpsee = { version = "0.24", features = ["http-client"] }
rand = "0.8"
rustc-hash = "*"
alloy = { version = "0.4.2", default-features = true, features = [
    "serde",
    "signers",
    "signer-keystore",
    "signer-mnemonic",
    "providers",
    "provider-http",
    "provider-ws",
    "network",
    "node-bindings",
    "consensus",
    "contract",
    "rpc-client",
    "rpc-client-ws",
    "rpc-types-eth",
    "eips",
    "rpc-types-debug",
    "rpc-types-trace",
    "json",
] }
alloy-sol-types = "0.8"
futures = "0.3.29"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
