/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface LiquidationTestInterface extends utils.Interface {
  functions: {
    "liquidate(address,address,address,uint256)": FunctionFragment;
    "liquidation()": FunctionFragment;
    "liquidationToken()": FunctionFragment;
    "setLiquidation(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "liquidate"
      | "liquidation"
      | "liquidationToken"
      | "setLiquidation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "liquidate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidation",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LiquidationTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LiquidationTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    liquidate(
      debtToken: PromiseOrValue<string>,
      collateralToken: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      repayAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    liquidation(overrides?: CallOverrides): Promise<[string]>;

    liquidationToken(overrides?: CallOverrides): Promise<[string]>;

    setLiquidation(
      _liquidation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  liquidate(
    debtToken: PromiseOrValue<string>,
    collateralToken: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    repayAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  liquidation(overrides?: CallOverrides): Promise<string>;

  liquidationToken(overrides?: CallOverrides): Promise<string>;

  setLiquidation(
    _liquidation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    liquidate(
      debtToken: PromiseOrValue<string>,
      collateralToken: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      repayAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidation(overrides?: CallOverrides): Promise<string>;

    liquidationToken(overrides?: CallOverrides): Promise<string>;

    setLiquidation(
      _liquidation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    liquidate(
      debtToken: PromiseOrValue<string>,
      collateralToken: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      repayAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    liquidation(overrides?: CallOverrides): Promise<BigNumber>;

    liquidationToken(overrides?: CallOverrides): Promise<BigNumber>;

    setLiquidation(
      _liquidation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    liquidate(
      debtToken: PromiseOrValue<string>,
      collateralToken: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      repayAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    liquidation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidationToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setLiquidation(
      _liquidation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
